### ISSUE TITLE
Widgetbot Commands

### ISSUE THREAD

**Issue by Futuza** [widgetbot-io/documentation#18]
Was just hoping someone would add a full list of commands to the [Widgetbot Docs](https://docs.widgetbot.io/) that you can use to manage the bot.  For example, using it to kick/ban users or `??setcolor background <color>` etc.

**Comment by SuzianeCundiff** [comment]
Is there a way to use another bot's commands?
I've tried to use an command from rod-bot but do not work out 😢

**Comment by advaith1** [comment]
@DarthFutuza (sorry for not responding earlier) you can get the list of message-based commands you can use with `??help`, but we plan to move all of our commands to slash commands and the moderation message commands so they will all be discoverable in Discord.
The moderation functionality is documented at https://docs.widgetbot.io/bot/moderation/ and there is a custom color guide at https://docs.widgetbot.io/guides/custom-colors/.

---

@SuzianeCundiff your comment is not related to WidgetBot's docs or this issue, but:
- users cannot use slash commands from WidgetBot; it is not possible for us to add bot slash commands to the widget due to a Discord limitation
- for old message-based bot commands, the bot can see messages sent through WidgetBot, but it may be choosing to ignore it. You'll need to talk to the developers of rod-bot for more information.

**Comment by SuzianeCundiff** [comment]
Got it.
Thank you for replying ^^
